apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "k8s-chart.fullname" . }}-canary"
  labels:
    {{- include "k8s-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-canary"
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.canary.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.canary.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.canary.resources | nindent 12 }}
